repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: check-ast
          - id: debug-statements
          - id: check-toml
          - id: check-json
          - id: check-xml
          - id: name-tests-test
            args: ["--pytest-test-first"]
    - repo: https://github.com/psf/black
      rev: 23.12.1
      hooks:
          - id: black
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.1.13
      hooks:
        - id: ruff
          types_or: [python, pyi, jupyter]
          args: [ --fix, --exit-non-zero-on-fix ]
